// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChatRequest represents a message from the user in a chat session
type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ContainerId   string                 `protobuf:"bytes,3,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	VolumePath    string                 `protobuf:"bytes,4,opt,name=volume_path,json=volumePath,proto3" json:"volume_path,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ChatRequest) GetVolumePath() string {
	if x != nil {
		return x.VolumePath
	}
	return ""
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ChatResponse represents a streaming response from the AI
type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ToolsUsed     []string               `protobuf:"bytes,2,rep,name=tools_used,json=toolsUsed,proto3" json:"tools_used,omitempty"`
	IsComplete    bool                   `protobuf:"varint,3,opt,name=is_complete,json=isComplete,proto3" json:"is_complete,omitempty"`
	ResponseType  string                 `protobuf:"bytes,4,opt,name=response_type,json=responseType,proto3" json:"response_type,omitempty"` // chat, error
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatResponse) GetToolsUsed() []string {
	if x != nil {
		return x.ToolsUsed
	}
	return nil
}

func (x *ChatResponse) GetIsComplete() bool {
	if x != nil {
		return x.IsComplete
	}
	return false
}

func (x *ChatResponse) GetResponseType() string {
	if x != nil {
		return x.ResponseType
	}
	return ""
}

func (x *ChatResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// TerminalInput represents a command executed in the terminal
type TerminalInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Pwd           string                 `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	VolumePath    string                 `protobuf:"bytes,3,opt,name=volume_path,json=volumePath,proto3" json:"volume_path,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Output        string                 `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp in seconds
	UserId        string                 `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DurationMs    int64                  `protobuf:"varint,8,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	HasOsc133     bool                   `protobuf:"varint,9,opt,name=has_osc133,json=hasOsc133,proto3" json:"has_osc133,omitempty"`
	SessionId     string                 `protobuf:"bytes,10,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ContainerId   string                 `protobuf:"bytes,11,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalInput) Reset() {
	*x = TerminalInput{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalInput) ProtoMessage() {}

func (x *TerminalInput) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalInput.ProtoReflect.Descriptor instead.
func (*TerminalInput) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *TerminalInput) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *TerminalInput) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

func (x *TerminalInput) GetVolumePath() string {
	if x != nil {
		return x.VolumePath
	}
	return ""
}

func (x *TerminalInput) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TerminalInput) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TerminalInput) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TerminalInput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TerminalInput) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TerminalInput) GetHasOsc133() bool {
	if x != nil {
		return x.HasOsc133
	}
	return false
}

func (x *TerminalInput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalInput) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

// AgentResponse represents the AI's response to a terminal input
type AgentResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // safety, pattern, llm, silent, error
	Content        string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Sidebar        string                 `protobuf:"bytes,3,opt,name=sidebar,proto3" json:"sidebar,omitempty"`
	Silent         bool                   `protobuf:"varint,4,opt,name=silent,proto3" json:"silent,omitempty"`
	Alert          string                 `protobuf:"bytes,5,opt,name=alert,proto3" json:"alert,omitempty"`
	RequireConfirm bool                   `protobuf:"varint,6,opt,name=require_confirm,json=requireConfirm,proto3" json:"require_confirm,omitempty"`
	Pattern        string                 `protobuf:"bytes,7,opt,name=pattern,proto3" json:"pattern,omitempty"`
	ToolsUsed      []string               `protobuf:"bytes,8,rep,name=tools_used,json=toolsUsed,proto3" json:"tools_used,omitempty"`
	Block          bool                   `protobuf:"varint,9,opt,name=block,proto3" json:"block,omitempty"`
	UserId         string                 `protobuf:"bytes,10,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentResponse) Reset() {
	*x = AgentResponse{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResponse) ProtoMessage() {}

func (x *AgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResponse.ProtoReflect.Descriptor instead.
func (*AgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AgentResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AgentResponse) GetSidebar() string {
	if x != nil {
		return x.Sidebar
	}
	return ""
}

func (x *AgentResponse) GetSilent() bool {
	if x != nil {
		return x.Silent
	}
	return false
}

func (x *AgentResponse) GetAlert() string {
	if x != nil {
		return x.Alert
	}
	return ""
}

func (x *AgentResponse) GetRequireConfirm() bool {
	if x != nil {
		return x.RequireConfirm
	}
	return false
}

func (x *AgentResponse) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *AgentResponse) GetToolsUsed() []string {
	if x != nil {
		return x.ToolsUsed
	}
	return nil
}

func (x *AgentResponse) GetBlock() bool {
	if x != nil {
		return x.Block
	}
	return false
}

func (x *AgentResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// HealthRequest for health check
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

// HealthResponse indicates service health status
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "ready", "not_ready", "degraded"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// SessionSignalRequest syncs transient learner signals with Python session state.
type SessionSignalRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId         string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	InEditorMode      bool                   `protobuf:"varint,3,opt,name=in_editor_mode,json=inEditorMode,proto3" json:"in_editor_mode,omitempty"`
	IsTyping          bool                   `protobuf:"varint,4,opt,name=is_typing,json=isTyping,proto3" json:"is_typing,omitempty"`
	JustSelfCorrected bool                   `protobuf:"varint,5,opt,name=just_self_corrected,json=justSelfCorrected,proto3" json:"just_self_corrected,omitempty"`
	EditorName        string                 `protobuf:"bytes,6,opt,name=editor_name,json=editorName,proto3" json:"editor_name,omitempty"`
	Timestamp         int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SessionSignalRequest) Reset() {
	*x = SessionSignalRequest{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSignalRequest) ProtoMessage() {}

func (x *SessionSignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSignalRequest.ProtoReflect.Descriptor instead.
func (*SessionSignalRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *SessionSignalRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionSignalRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionSignalRequest) GetInEditorMode() bool {
	if x != nil {
		return x.InEditorMode
	}
	return false
}

func (x *SessionSignalRequest) GetIsTyping() bool {
	if x != nil {
		return x.IsTyping
	}
	return false
}

func (x *SessionSignalRequest) GetJustSelfCorrected() bool {
	if x != nil {
		return x.JustSelfCorrected
	}
	return false
}

func (x *SessionSignalRequest) GetEditorName() string {
	if x != nil {
		return x.EditorName
	}
	return ""
}

func (x *SessionSignalRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// SessionSignalResponse acknowledges session signal updates.
type SessionSignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionSignalResponse) Reset() {
	*x = SessionSignalResponse{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSignalResponse) ProtoMessage() {}

func (x *SessionSignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSignalResponse.ProtoReflect.Descriptor instead.
func (*SessionSignalResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *SessionSignalResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SessionSignalResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// SessionData represents learner session state stored in Redis
type SessionData struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ContainerId         string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	VolumePath          string                 `protobuf:"bytes,3,opt,name=volume_path,json=volumePath,proto3" json:"volume_path,omitempty"`
	InEditorMode        bool                   `protobuf:"varint,4,opt,name=in_editor_mode,json=inEditorMode,proto3" json:"in_editor_mode,omitempty"`
	AttemptCount        int32                  `protobuf:"varint,5,opt,name=attempt_count,json=attemptCount,proto3" json:"attempt_count,omitempty"`
	JustSelfCorrected   bool                   `protobuf:"varint,6,opt,name=just_self_corrected,json=justSelfCorrected,proto3" json:"just_self_corrected,omitempty"`
	IsTyping            bool                   `protobuf:"varint,7,opt,name=is_typing,json=isTyping,proto3" json:"is_typing,omitempty"`
	LastProactiveMsg    int64                  `protobuf:"varint,8,opt,name=last_proactive_msg,json=lastProactiveMsg,proto3" json:"last_proactive_msg,omitempty"` // Unix timestamp
	CreatedAt           int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ConversationHistory []*ConversationMessage `protobuf:"bytes,11,rep,name=conversation_history,json=conversationHistory,proto3" json:"conversation_history,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SessionData) Reset() {
	*x = SessionData{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionData) ProtoMessage() {}

func (x *SessionData) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionData.ProtoReflect.Descriptor instead.
func (*SessionData) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *SessionData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionData) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *SessionData) GetVolumePath() string {
	if x != nil {
		return x.VolumePath
	}
	return ""
}

func (x *SessionData) GetInEditorMode() bool {
	if x != nil {
		return x.InEditorMode
	}
	return false
}

func (x *SessionData) GetAttemptCount() int32 {
	if x != nil {
		return x.AttemptCount
	}
	return 0
}

func (x *SessionData) GetJustSelfCorrected() bool {
	if x != nil {
		return x.JustSelfCorrected
	}
	return false
}

func (x *SessionData) GetIsTyping() bool {
	if x != nil {
		return x.IsTyping
	}
	return false
}

func (x *SessionData) GetLastProactiveMsg() int64 {
	if x != nil {
		return x.LastProactiveMsg
	}
	return 0
}

func (x *SessionData) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SessionData) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *SessionData) GetConversationHistory() []*ConversationMessage {
	if x != nil {
		return x.ConversationHistory
	}
	return nil
}

// ConversationMessage represents a single message in conversation history
type ConversationMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // user, assistant, system
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationMessage) Reset() {
	*x = ConversationMessage{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationMessage) ProtoMessage() {}

func (x *ConversationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationMessage.ProtoReflect.Descriptor instead.
func (*ConversationMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ConversationMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ConversationMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ConversationMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x05agent\"\xa3\x01\n" +
	"\vChatRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fcontainer_id\x18\x03 \x01(\tR\vcontainerId\x12\x1f\n" +
	"\vvolume_path\x18\x04 \x01(\tR\n" +
	"volumePath\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\"\xb2\x01\n" +
	"\fChatResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"tools_used\x18\x02 \x03(\tR\ttoolsUsed\x12\x1f\n" +
	"\vis_complete\x18\x03 \x01(\bR\n" +
	"isComplete\x12#\n" +
	"\rresponse_type\x18\x04 \x01(\tR\fresponseType\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\xca\x02\n" +
	"\rTerminalInput\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x10\n" +
	"\x03pwd\x18\x02 \x01(\tR\x03pwd\x12\x1f\n" +
	"\vvolume_path\x18\x03 \x01(\tR\n" +
	"volumePath\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06output\x18\x05 \x01(\tR\x06output\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userId\x12\x1f\n" +
	"\vduration_ms\x18\b \x01(\x03R\n" +
	"durationMs\x12\x1d\n" +
	"\n" +
	"has_osc133\x18\t \x01(\bR\thasOsc133\x12\x1d\n" +
	"\n" +
	"session_id\x18\n" +
	" \x01(\tR\tsessionId\x12!\n" +
	"\fcontainer_id\x18\v \x01(\tR\vcontainerId\"\x96\x02\n" +
	"\rAgentResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x18\n" +
	"\asidebar\x18\x03 \x01(\tR\asidebar\x12\x16\n" +
	"\x06silent\x18\x04 \x01(\bR\x06silent\x12\x14\n" +
	"\x05alert\x18\x05 \x01(\tR\x05alert\x12'\n" +
	"\x0frequire_confirm\x18\x06 \x01(\bR\x0erequireConfirm\x12\x18\n" +
	"\apattern\x18\a \x01(\tR\apattern\x12\x1d\n" +
	"\n" +
	"tools_used\x18\b \x03(\tR\ttoolsUsed\x12\x14\n" +
	"\x05block\x18\t \x01(\bR\x05block\x12\x17\n" +
	"\auser_id\x18\n" +
	" \x01(\tR\x06userId\"\x0f\n" +
	"\rHealthRequest\"z\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\x80\x02\n" +
	"\x14SessionSignalRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12$\n" +
	"\x0ein_editor_mode\x18\x03 \x01(\bR\finEditorMode\x12\x1b\n" +
	"\tis_typing\x18\x04 \x01(\bR\bisTyping\x12.\n" +
	"\x13just_self_corrected\x18\x05 \x01(\bR\x11justSelfCorrected\x12\x1f\n" +
	"\veditor_name\x18\x06 \x01(\tR\n" +
	"editorName\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\"?\n" +
	"\x15SessionSignalResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xbd\x03\n" +
	"\vSessionData\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x1f\n" +
	"\vvolume_path\x18\x03 \x01(\tR\n" +
	"volumePath\x12$\n" +
	"\x0ein_editor_mode\x18\x04 \x01(\bR\finEditorMode\x12#\n" +
	"\rattempt_count\x18\x05 \x01(\x05R\fattemptCount\x12.\n" +
	"\x13just_self_corrected\x18\x06 \x01(\bR\x11justSelfCorrected\x12\x1b\n" +
	"\tis_typing\x18\a \x01(\bR\bisTyping\x12,\n" +
	"\x12last_proactive_msg\x18\b \x01(\x03R\x10lastProactiveMsg\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\x12M\n" +
	"\x14conversation_history\x18\v \x03(\v2\x1a.agent.ConversationMessageR\x13conversationHistory\"a\n" +
	"\x13ConversationMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp2\x8c\x02\n" +
	"\fAgentService\x121\n" +
	"\x04Chat\x12\x12.agent.ChatRequest\x1a\x13.agent.ChatResponse0\x01\x12?\n" +
	"\x0fProcessTerminal\x12\x14.agent.TerminalInput\x1a\x14.agent.AgentResponse0\x01\x12Q\n" +
	"\x14UpdateSessionSignals\x12\x1b.agent.SessionSignalRequest\x1a\x1c.agent.SessionSignalResponse\x125\n" +
	"\x06Health\x12\x14.agent.HealthRequest\x1a\x15.agent.HealthResponseB4Z2github.com/ashureev/shsh-labs/internal/proto/agentb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_agent_proto_goTypes = []any{
	(*ChatRequest)(nil),           // 0: agent.ChatRequest
	(*ChatResponse)(nil),          // 1: agent.ChatResponse
	(*TerminalInput)(nil),         // 2: agent.TerminalInput
	(*AgentResponse)(nil),         // 3: agent.AgentResponse
	(*HealthRequest)(nil),         // 4: agent.HealthRequest
	(*HealthResponse)(nil),        // 5: agent.HealthResponse
	(*SessionSignalRequest)(nil),  // 6: agent.SessionSignalRequest
	(*SessionSignalResponse)(nil), // 7: agent.SessionSignalResponse
	(*SessionData)(nil),           // 8: agent.SessionData
	(*ConversationMessage)(nil),   // 9: agent.ConversationMessage
}
var file_agent_proto_depIdxs = []int32{
	9, // 0: agent.SessionData.conversation_history:type_name -> agent.ConversationMessage
	0, // 1: agent.AgentService.Chat:input_type -> agent.ChatRequest
	2, // 2: agent.AgentService.ProcessTerminal:input_type -> agent.TerminalInput
	6, // 3: agent.AgentService.UpdateSessionSignals:input_type -> agent.SessionSignalRequest
	4, // 4: agent.AgentService.Health:input_type -> agent.HealthRequest
	1, // 5: agent.AgentService.Chat:output_type -> agent.ChatResponse
	3, // 6: agent.AgentService.ProcessTerminal:output_type -> agent.AgentResponse
	7, // 7: agent.AgentService.UpdateSessionSignals:output_type -> agent.SessionSignalResponse
	5, // 8: agent.AgentService.Health:output_type -> agent.HealthResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
